<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows7.0</TargetFramework>
		<UseWPF>true</UseWPF>
		<Authors>Aqi Tech Tips</Authors>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageId>AQI.HtmlTextBlock</PackageId>
		<PackageLicenseExpression></PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/aqibbanday/HtmlTextBlock</PackageProjectUrl>
		<RepositoryUrl>https://github.com/aqibbanday/HtmlTextBlock</RepositoryUrl>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
		<PackageTags>HtmlTextBlock</PackageTags>
		<Title>HtmlTextBlock</Title>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<DebugType>full</DebugType>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<DebugType>pdbonly</DebugType>
	</PropertyGroup>
	<ItemGroup>
		<None Include="..\LICENSE.md">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
		<None Include="Defines\DependencyProperty.cs" />
		<None Include="Defines\Header.cs" />
		<None Include="Defines\PropertyList.cs" />
		<None Include="Defines\Stylelist.cs" />
		<None Include="Defines\Utils.cs" />
	</ItemGroup>
	<ItemGroup>
		<Compile Remove="Defines\DependencyProperty.cs" />
		<Compile Remove="Defines\Header.cs" />
		<Compile Remove="Defines\PropertyList.cs" />
		<Compile Remove="Defines\Stylelist.cs" />
		<Compile Remove="Defines\Utils.cs" />
		<Compile Remove="RT\ColorConverter.cs" />
	</ItemGroup>
</Project>